---
- name: Inserir flavour {{ fix_flavour_target }} no banco
  ansible.builtin.shell: |
    psql -h {{ db.host }} -p {{ db.port }} -U {{ db.user }} -d {{ db.name }} -X -q -v ON_ERROR_STOP=1 << 'EOF'
    INSERT INTO tb_fix_server_configuration_flavour
      (cd_flavour, ds_flavour, allow_dropcopy, queue_mq_fix_acceptor)
    VALUES
      ('AGORA-MOCK-TEST', 'Sessões de Mock com ambiente de Produção da Bolsa', false, NULL)
    ON CONFLICT (cd_flavour) DO NOTHING;
    EOF
  register: flavour_insert
  failed_when: false
  changed_when: false
  environment:
    PGPASSWORD: "{{ db.password }}"
  delegate_to: AG-AH-CL-BD-166.agorasenior.corp

- name: Normalizar escolha de FEED-C DR
  ansible.builtin.set_fact:
    enable_feed_c_dr: >-
      {{
        (feed_c_dr_choice | default('Não') | lower)
        in ['sim', 's', 'yes', 'y', 'true', '1']
      }}

- name: Carregar queries de inserts (dia anterior)
  ansible.builtin.include_vars:
    file: "queries/inserts.yml"

- name: Carregar queries extras de FEED-C DR (se habilitado)
  ansible.builtin.include_vars:
    file: "queries/inserts_feed_c_dr.yml"
  when: enable_feed_c_dr

- name: Montar lista final de INSERTs
  ansible.builtin.set_fact:
    _insert_queries_effective: >-
      {{
        (insert_queries_feed_c_dr | default([])) +
        (insert_queries | default([]))
      }}

- name: Executar INSERTs de dia_anterior
  ansible.builtin.shell: |
    psql -h {{ db.host }} -p {{ db.port }} -U {{ db.user }} -d {{ db.name }} -X -q -v ON_ERROR_STOP=1 << 'EOF'
    {{ _sql_effective }}
    EOF
  loop: "{{ _insert_queries_effective }}"
  loop_control:
    label: "{{ item.name | default('INSERT') }}"
  vars:
    _sql_effective: >-
      {{
        (item.sql | default('') | trim)
        if (
          (item.sql is not defined)
          or ('insert into' not in (item.sql | lower))
          or ('on conflict' in (item.sql | lower))
        )
        else (
          (item.sql | trim)
          | regex_replace(';\s*$', '')
          ~ ' ON CONFLICT DO NOTHING;'
        )
      }}
  register: db_inserts
  failed_when: false
  changed_when: false
  environment:
    PGPASSWORD: "{{ db.password }}"
  delegate_to: AG-AH-CL-BD-166.agorasenior.corp

- name: Montar resumo de inserts
  ansible.builtin.set_fact:
    db_inserts_report:
      executed: true
      flavour:
        rc: "{{ flavour_insert.rc | default(0) }}"
        stdout: "{{ flavour_insert.stdout | default('') }}"
        stderr: "{{ flavour_insert.stderr | default('') }}"
      results: "{{ db_inserts.results | default([]) }}"
      errors_count: >-
        {{
          (
            (db_inserts.results | default([]))
            | selectattr('rc', 'defined')
            | selectattr('rc', 'ne', 0)
            | list
            | length
          )
          + (1 if ((flavour_insert.rc | default(0) | int) != 0) else 0)
        }}

