- name: Renderizar script async por namespace
  ansible.builtin.template:
    src: templates/execute_ns_async.sh.j2
    dest: "{{ tmp_path_local }}/execute_ns_async_{{ namespace }}.sh"
    mode: "0755"
  loop: "{{ item }}"
  loop_control:
    loop_var: namespace

- name: Namespace {{ namespace }} Scale Down/Up Paralelizado
  ansible.builtin.shell: "{{ tmp_path_local }}/execute_ns_async_{{ namespace }}.sh"
  async: 18000
  loop: "{{ item }}"
  loop_control:
    loop_var: namespace
  poll: 0
  register: async_results
  environment:
    TZ: "America/Sao_Paulo"

- name: Acompanhamento de status da tarefa assíncrona de scale up/down
  ansible.builtin.async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: async_result_item
  register: async_poll_results
  until: async_poll_results.finished
  retries: 18000
  delay: 1

- name: Consultar resultado da Migração Paralelizada
  ansible.builtin.shell: cat deployments_async*
  register: deployments_async

- name: Visualizar resultado da Migração Paralelizada
  ansible.builtin.debug:
    var: deployments_async
